---
- hosts: all
  tasks:
  - name: Create portainer container
    docker_container:
      name: my_portainer
      image: portainer/portainer
      state: started
      ports:
       - "9000:9000"
      restart_policy: always
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      privileged: "yes"