---
- hosts: all
  tasks:
  - name: Install pip
    apt:
      name: python-pip
      state: present
      update_cache: yes

  - name: install certain python modules for docker
    pip:
      name: "{{ item.name }}"
      state: present
    with_items:
     - { name: docker-py }